# Generated by Django 2.2.12 on 2022-03-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empcode', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=70)),
                ('score', models.IntegerField()),
                ('createdate', models.DateTimeField()),
                ('lastModified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
